version: 1
disable_existing_loggers: False
formatters:

  colored:
    "()": colorlog.ColoredFormatter
    format: '[%(asctime)s] - %(name)20s - %(log_color)s%(levelname)-8s%(reset)s %(blue)s%(message)s'
    log_colors:
      DEBUG: cyan
      INFO: green
      WARNING: yellow
      ERROR: red
      CRITICAL: 'red,bg_white'

handlers:
  default:
    formatter: colored
    class: logging.StreamHandler
    stream: ext://sys.stdout
  access:
    formatter: colored
    class: logging.StreamHandler
    stream: ext://sys.stdout

loggers:
  uvicorn.error:
    level: ERROR
    handlers:
      - default
    propagate: no

  uvicorn.access:
    level: ERROR
    handlers:
      - access
    propagate: no

  engineio.server:
    level: INFO
    handlers:
      - access
    propagate: no

  socketio.server:
    level: ERROR
    handlers:
      - access
    propagate: no

  asyncio:
    level: ERROR
    handlers:
      - access
    propagate: no

root:
  level: DEBUG
  handlers:
    - default
  propagate: no